# https://github.com/marketplace/actions/ftp-deploy
# Automatically send code to FTP server on changes

on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.ultimatefreehost.in
        username: ltm_28498913
        password: rakesh@solarunited.org
